apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-notifications-task
  namespace: ml-pipeline
  labels:
    app.kubernetes.io/name: cleanup-notifications-task
    app.kubernetes.io/component: pipeline
spec:
  description: "Cleanup resources and send notifications"
  params:
    - name: jira-url
      type: string
      description: "Jira server URL"
    - name: jira-project-key
      type: string
      description: "Jira project key"
  workspaces:
    - name: source
      description: "Source code workspace"
    - name: artifacts
      description: "Artifacts workspace"
    - name: attestations
      description: "Attestations workspace"
  steps:
    - name: cleanup-notifications
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Cleaning up resources and sending notifications..."
        echo "Jira URL: $(params.jira-url)"
        echo "Jira Project: $(params.jira-project-key)"
        echo "✅ Cleanup and notifications completed"
      workingDir: $(workspaces.artifacts.path)
