apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s-task
  namespace: ml-pipeline
  labels:
    app.kubernetes.io/name: deploy-to-k8s-task
    app.kubernetes.io/component: pipeline
spec:
  description: "Deploy application to Kubernetes cluster"
  params:
    - name: image-name
      type: string
      description: "Container image name"
    - name: image-tag
      type: string
      description: "Container image tag"
    - name: environment
      type: string
      description: "Target environment"
      default: "staging"
  workspaces:
    - name: source
      description: "Source code workspace"
    - name: artifacts
      description: "Artifacts workspace"
  steps:
    - name: deploy-to-k8s
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to Kubernetes..."
        echo "Image: $(params.image-name):$(params.image-tag)"
        echo "Environment: $(params.environment)"
        echo "✅ Application deployed to Kubernetes"
      workingDir: $(workspaces.source.path)
