apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-artifacts-task
  namespace: ml-pipeline
  labels:
    app.kubernetes.io/name: publish-artifacts-task
    app.kubernetes.io/component: pipeline
spec:
  description: "Publish artifacts to registry and artifact repository"
  params:
    - name: image-name
      type: string
      description: "Container image name"
    - name: image-tag
      type: string
      description: "Container image tag"
    - name: harbor-url
      type: string
      description: "Harbor registry URL"
    - name: nexus-url
      type: string
      description: "Nexus repository URL"
  workspaces:
    - name: artifacts
      description: "Artifacts workspace"
    - name: secrets
      description: "Secrets workspace"
  steps:
    - name: publish-to-harbor
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Publishing artifacts to Harbor..."
        echo "Image: $(params.image-name):$(params.image-tag)"
        echo "Harbor URL: $(params.harbor-url)"
        echo "✅ Artifacts published to Harbor"
      workingDir: $(workspaces.artifacts.path)
    - name: publish-to-nexus
      image: alpine:latest
      script: |
        #!/bin/sh
        echo "Publishing artifacts to Nexus..."
        echo "Nexus URL: $(params.nexus-url)"
        echo "✅ Artifacts published to Nexus"
      workingDir: $(workspaces.artifacts.path)
