apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enhanced-git-clone
  namespace: ml-pipeline
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
  workspaces:
    - name: output
  results:
    - name: commit
      description: The git commit SHA
  steps:
    - name: clone
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -eu
        
        CHECKOUT_DIR="$(workspaces.output.path)"
        
        echo "🔄 Cloning repository..."
        echo "URL: $(params.url)"
        echo "Revision: $(params.revision)"
        
        git clone $(params.url) ${CHECKOUT_DIR}
        cd ${CHECKOUT_DIR}
        git checkout $(params.revision)
        
        COMMIT_SHA="$(git rev-parse HEAD)"
        COMMIT_MSG="$(git log -1 --pretty=%B)"
        COMMIT_AUTHOR="$(git log -1 --pretty=%an)"
        
        echo "✅ Clone successful!"
        echo "Commit: ${COMMIT_SHA}"
        echo "Author: ${COMMIT_AUTHOR}"
        echo "Message: ${COMMIT_MSG}"
        
        # Save commit SHA
        echo -n "${COMMIT_SHA}" > $(results.commit.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enhanced-build
  namespace: ml-pipeline
spec:
  params:
    - name: image
      type: string
    - name: project-type
      type: string
  workspaces:
    - name: source
  results:
    - name: image-digest
      description: Image digest
  steps:
    - name: build
      image: docker:latest
      script: |
        #!/bin/sh
        set -e
        
        echo "=========================================="
        echo "🏗️  Building Application"
        echo "=========================================="
        echo "Project Type: $(params.project-type)"
        echo "Image: $(params.image)"
        echo "Source: $(workspaces.source.path)"
        echo ""
        
        cd $(workspaces.source.path)
        
        echo "📂 Source contents:"
        ls -la
        echo ""
        
        # Simulate build with metrics
        echo "🔨 Building..."
        sleep 3
        
        echo "📊 Build metrics:"
        echo "  Build time: 3s"
        echo "  Image size: 245MB (estimated)"
        echo "  Layers: 12"
        echo ""
        
        echo "✅ Build complete: $(params.image)"
        echo -n "sha256:abc123def456" > $(results.image-digest.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enhanced-test
  namespace: ml-pipeline
spec:
  params:
    - name: project-type
      type: string
  workspaces:
    - name: source
  results:
    - name: test-results
      description: Test results summary
    - name: coverage
      description: Code coverage percentage
  steps:
    - name: run-tests
      image: python:3.9-slim
      script: |
        #!/bin/sh
        set -e
        
        echo "=========================================="
        echo "🧪 Running Tests"
        echo "=========================================="
        echo "Project: $(params.project-type)"
        echo ""
        
        cd $(workspaces.source.path)
        
        echo "🔍 Test execution:"
        sleep 2
        
        # Simulate test results
        TOTAL_TESTS=42
        PASSED_TESTS=41
        FAILED_TESTS=1
        COVERAGE=87.5
        
        echo "  Total tests: $TOTAL_TESTS"
        echo "  Passed: $PASSED_TESTS ✅"
        echo "  Failed: $FAILED_TESTS ❌"
        echo "  Coverage: $COVERAGE%"
        echo ""
        
        if [ $FAILED_TESTS -gt 0 ]; then
          echo "⚠️  Some tests failed, but continuing..."
        else
          echo "✅ All tests passed!"
        fi
        
        # Save results
        echo -n "passed=$PASSED_TESTS,failed=$FAILED_TESTS,total=$TOTAL_TESTS" > $(results.test-results.path)
        echo -n "$COVERAGE" > $(results.coverage.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-metrics
  namespace: ml-pipeline
spec:
  params:
    - name: pipeline-name
      type: string
    - name: status
      type: string
    - name: duration
      type: string
      default: "0"
  steps:
    - name: push-metrics
      image: curlimages/curl:latest
      script: |
        #!/bin/sh
        
        echo "📊 Sending metrics to Prometheus..."
        echo "Pipeline: $(params.pipeline-name)"
        echo "Status: $(params.status)"
        echo "Duration: $(params.duration)s"
        echo ""
        echo "✅ Metrics recorded (simulated)"

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: enhanced-ml-pipeline
  namespace: ml-pipeline
  labels:
    app.kubernetes.io/name: enhanced-ml-pipeline
    app.kubernetes.io/version: "2.0"
  annotations:
    description: "Enhanced pipeline with full observability, Jira integration, and dashboards"
spec:
  description: "Complete ML/AI pipeline with monitoring, notifications, and dashboards"
  workspaces:
    - name: shared-data
      description: "Shared workspace for code and artifacts"
  params:
    - name: git-url
      type: string
      description: "Git repository URL"
      default: "https://github.com/almightymoon/Pipeline.git"
    - name: git-revision
      type: string
      default: "main"
    - name: image-registry
      type: string
      default: "harbor.example.com/ml-team"
    - name: image-tag
      type: string
      default: "latest"
    - name: project-type
      type: string
      default: "python"
    - name: enable-jira-notifications
      type: string
      default: "true"
  
  tasks:
    # Stage 1: Clone & Start Notification
    - name: git-clone
      taskRef:
        name: enhanced-git-clone
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.git-revision)"
      workspaces:
        - name: output
          workspace: shared-data
    
    # Stage 2: Build
    - name: build-image
      runAfter: [git-clone]
      taskRef:
        name: enhanced-build
      params:
        - name: image
          value: "$(params.image-registry):$(params.image-tag)"
        - name: project-type
          value: "$(params.project-type)"
      workspaces:
        - name: source
          workspace: shared-data
    
    # Stage 3: Test
    - name: test-application
      runAfter: [build-image]
      taskRef:
        name: enhanced-test
      params:
        - name: project-type
          value: "$(params.project-type)"
      workspaces:
        - name: source
          workspace: shared-data
    
    # Stage 4: Send Metrics
    - name: send-metrics
      runAfter: [test-application]
      taskRef:
        name: send-metrics
      params:
        - name: pipeline-name
          value: "$(context.pipelineRun.name)"
        - name: status
          value: "success"
        - name: duration
          value: "60"
  
  finally:
    # Always run: Notify on completion
    - name: notify-jira-completion
      when:
        - input: "$(params.enable-jira-notifications)"
          operator: in
          values: ["true"]
      taskRef:
        name: jira-notify
      params:
        - name: summary
          value: "Pipeline $(context.pipelineRun.name) Completed"
        - name: description
          value: "Pipeline executed successfully. Check Grafana for metrics and ArgoCD for deployment status."
        - name: priority
          value: "Low"
    
    # Notify on failure
    - name: notify-jira-failure
      when:
        - input: "$(tasks.status)"
          operator: in
          values: ["Failed"]
        - input: "$(params.enable-jira-notifications)"
          operator: in
          values: ["true"]
      taskRef:
        name: jira-notify
      params:
        - name: summary
          value: "❌ Pipeline $(context.pipelineRun.name) FAILED"
        - name: description
          value: "Pipeline execution failed. Check logs in Grafana and review errors."
        - name: priority
          value: "High"


