# ===========================================================
# SECURE CONFIGURATION TEMPLATE
# Replace all hardcoded values with environment variables
# ===========================================================

# Grafana Configuration
grafana:
  url: "${GRAFANA_URL:-http://localhost:3000}"
  username: "${GRAFANA_USERNAME:-admin}"
  password: "${GRAFANA_PASSWORD}"  # REQUIRED - no default
  admin_password: "${GRAFANA_ADMIN_PASSWORD}"  # REQUIRED - no default

# Keycloak Configuration  
keycloak:
  url: "${KEYCLOAK_URL:-http://localhost:8080}"
  admin_username: "${KEYCLOAK_ADMIN_USERNAME:-admin}"
  admin_password: "${KEYCLOAK_ADMIN_PASSWORD}"  # REQUIRED - no default
  realm: "${KEYCLOAK_REALM:-ml-pipeline}"

# Harbor Registry Configuration
harbor:
  url: "${HARBOR_URL:-http://localhost}"
  username: "${HARBOR_USERNAME:-admin}"
  password: "${HARBOR_PASSWORD}"  # REQUIRED - no default

# SonarQube Configuration
sonarqube:
  url: "${SONARQUBE_URL:-http://localhost:9000}"
  token: "${SONARQUBE_TOKEN}"  # REQUIRED - no default

# Jira Configuration
jira:
  url: "${JIRA_URL:-http://localhost:8080}"
  email: "${JIRA_EMAIL}"  # REQUIRED - no default
  api_token: "${JIRA_API_TOKEN}"  # REQUIRED - no default
  project_key: "${JIRA_PROJECT_KEY:-MLP}"

# Kubernetes Configuration
kubernetes:
  server_url: "${K8S_SERVER_URL}"  # REQUIRED - no default
  kubeconfig: "${KUBECONFIG}"  # REQUIRED - base64 encoded

# Vault Configuration
vault:
  url: "${VAULT_URL:-http://localhost:8200}"
  token: "${VAULT_TOKEN}"  # REQUIRED - no default

# Prometheus Configuration
prometheus:
  url: "${PROMETHEUS_URL:-http://localhost:9090}"
  pushgateway_url: "${PROMETHEUS_PUSHGATEWAY_URL:-http://localhost:9091}"

# Security Notes:
# 1. All passwords and tokens MUST be provided via environment variables
# 2. Never commit actual credentials to version control
# 3. Use strong, unique passwords for each service
# 4. Rotate credentials regularly
# 5. Use secrets management (Vault, Kubernetes secrets, etc.)
