apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: REPO_NAME_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: REPO_NAME_PLACEHOLDER
  template:
    metadata:
      labels:
        app: REPO_NAME_PLACEHOLDER
    spec:
      containers:
      - name: REPO_NAME_PLACEHOLDER
        image: IMAGE_NAME_PLACEHOLDER
        imagePullPolicy: IfNotPresent
        # Let the application run with its default command from Dockerfile
        # Only override for specific applications that need custom entrypoint detection
        # command: ["/bin/sh", "-c"]
        # args:
        #   - |
        #     # Custom entrypoint detection logic removed - let Dockerfile CMD run
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        - name: http-3000
          containerPort: 3000
          protocol: TCP
        - name: http-8000
          containerPort: 8000
          protocol: TCP
        - name: http-8080
          containerPort: 8080
          protocol: TCP
        env:
        - name: REPO_NAME
          value: "REPO_NAME_PLACEHOLDER"
        - name: REPO_URL
          value: "REPO_URL_PLACEHOLDER"
        - name: PIPELINE_RUN
          value: "RUN_NUMBER_PLACEHOLDER"
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: REPO_NAME_PLACEHOLDER
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: NODE_PORT_PLACEHOLDER
  selector:
    app: REPO_NAME_PLACEHOLDER
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: INGRESS_NAME_PLACEHOLDER
  namespace: NAMESPACE_PLACEHOLDER
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: HOST_NAME_PLACEHOLDER
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: SERVICE_NAME_PLACEHOLDER
            port:
              number: 80