apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
  labels:
    app: prometheus-pushgateway
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
