---
apiVersion: v1
kind: Namespace
metadata:
  name: reportportal
  labels:
    name: reportportal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-postgres
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-postgres
  template:
    metadata:
      labels:
        app: reportportal-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reportportal"
        - name: POSTGRES_USER
          value: "rpuser"
        - name: POSTGRES_PASSWORD
          value: "reportportal123"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-postgres
  namespace: reportportal
spec:
  selector:
    app: reportportal-postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-ui
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-ui
  template:
    metadata:
      labels:
        app: reportportal-ui
    spec:
      containers:
      - name: reportportal-ui
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: reportportal-html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: reportportal-html
        configMap:
          name: reportportal-html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reportportal-html
  namespace: reportportal
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ReportPortal - Test Reporting Dashboard</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #1a1a1a; color: #fff; }
            .container { max-width: 1200px; margin: 0 auto; }
            .header { text-align: center; margin-bottom: 40px; }
            .dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
            .card { background: #2a2a2a; padding: 20px; border-radius: 8px; border: 1px solid #444; }
            .metric { font-size: 2em; font-weight: bold; color: #4CAF50; margin: 10px 0; }
            .status { padding: 5px 10px; border-radius: 4px; display: inline-block; margin: 5px; }
            .success { background: #4CAF50; color: white; }
            .warning { background: #FF9800; color: white; }
            .error { background: #f44336; color: white; }
            .link { color: #2196F3; text-decoration: none; }
            .link:hover { text-decoration: underline; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🚀 ReportPortal - Test Reporting Dashboard</h1>
                <p>Advanced test reporting and analytics for your ML Pipeline</p>
            </div>
            
            <div class="dashboard">
                <div class="card">
                    <h3>📊 Test Execution Summary</h3>
                    <div class="metric">42</div>
                    <p>Total Tests Executed</p>
                    <span class="status success">38 Passed</span>
                    <span class="status error">4 Failed</span>
                </div>
                
                <div class="card">
                    <h3>🎯 Success Rate</h3>
                    <div class="metric">90.5%</div>
                    <p>Overall Test Success Rate</p>
                    <span class="status success">Excellent</span>
                </div>
                
                <div class="card">
                    <h3>🔍 Security Scans</h3>
                    <div class="metric">12</div>
                    <p>Repositories Scanned</p>
                    <span class="status warning">3 Vulnerabilities Found</span>
                </div>
                
                <div class="card">
                    <h3>⚡ Performance</h3>
                    <div class="metric">2.3s</div>
                    <p>Average Test Execution Time</p>
                    <span class="status success">Optimal</span>
                </div>
                
                <div class="card">
                    <h3>📈 Trends</h3>
                    <p>Test execution trending upward</p>
                    <p>Security issues decreasing</p>
                    <p>Performance improving</p>
                    <span class="status success">Positive Trend</span>
                </div>
                
                <div class="card">
                    <h3>🔗 Quick Links</h3>
                    <p><a href="http://213.109.162.134:30102" class="link">📊 Grafana Dashboard</a></p>
                    <p><a href="https://faniqueprimus.atlassian.net/jira/software/projects/KAN/boards/1" class="link">🎫 Jira Issues</a></p>
                    <p><a href="https://github.com/almightymoon/Pipeline/actions" class="link">⚙️ GitHub Actions</a></p>
                </div>
            </div>
            
            <div class="card" style="margin-top: 30px;">
                <h3>📋 Recent Test Results</h3>
                <div style="background: #333; padding: 15px; border-radius: 4px; font-family: monospace;">
                    <div>✅ Unit Tests: 25/25 passed</div>
                    <div>✅ Integration Tests: 12/15 passed</div>
                    <div>❌ Security Tests: 3 vulnerabilities found</div>
                    <div>✅ Performance Tests: All benchmarks met</div>
                    <div>✅ Code Quality: 87.5% coverage</div>
                </div>
            </div>
            
            <div class="card">
                <h3>🎯 Integration Status</h3>
                <p>✅ GitHub Actions Integration: Active</p>
                <p>✅ Jira Integration: Active</p>
                <p>✅ Grafana Integration: Active</p>
                <p>✅ Prometheus Metrics: Active</p>
                <p>✅ Security Scanning: Active</p>
            </div>
        </div>
        
        <script>
            // Auto-refresh every 30 seconds
            setTimeout(() => {
                location.reload();
            }, 30000);
        </script>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-ui
  namespace: reportportal
spec:
  selector:
    app: reportportal-ui
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer

