---
apiVersion: v1
kind: Namespace
metadata:
  name: reportportal
  labels:
    name: reportportal

---
apiVersion: v1
kind: Secret
metadata:
  name: reportportal-secrets
  namespace: reportportal
type: Opaque
stringData:
  postgres-password: "reportportal123"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: reportportal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reportportal"
        - name: POSTGRES_USER
          value: "rpuser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: reportportal
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-migrations
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-migrations
  template:
    metadata:
      labels:
        app: reportportal-migrations
    spec:
      containers:
      - name: migrations
        image: reportportal/service-authorization:5.7.4
        env:
        - name: RP_DB_HOST
          value: "postgres"
        - name: RP_DB_PORT
          value: "5432"
        - name: RP_DB_NAME
          value: "reportportal"
        - name: RP_DB_USER
          value: "rpuser"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        command: ["java", "-jar", "app.jar", "--spring.profiles.active=docker"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-authorization
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-authorization
  template:
    metadata:
      labels:
        app: reportportal-authorization
    spec:
      containers:
      - name: authorization
        image: reportportal/service-authorization:5.7.4
        ports:
        - containerPort: 9999
        env:
        - name: RP_DB_HOST
          value: "postgres"
        - name: RP_DB_PORT
          value: "5432"
        - name: RP_DB_NAME
          value: "reportportal"
        - name: RP_DB_USER
          value: "rpuser"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-authorization
  namespace: reportportal
spec:
  selector:
    app: reportportal-authorization
  ports:
  - port: 9999
    targetPort: 9999

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-api
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-api
  template:
    metadata:
      labels:
        app: reportportal-api
    spec:
      containers:
      - name: api
        image: reportportal/service-api:5.7.4
        ports:
        - containerPort: 8585
        env:
        - name: RP_DB_HOST
          value: "postgres"
        - name: RP_DB_PORT
          value: "5432"
        - name: RP_DB_NAME
          value: "reportportal"
        - name: RP_DB_USER
          value: "rpuser"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        - name: RP_SERVER_PORT
          value: "8585"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-api
  namespace: reportportal
spec:
  selector:
    app: reportportal-api
  ports:
  - port: 8585
    targetPort: 8585

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-ui
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-ui
  template:
    metadata:
      labels:
        app: reportportal-ui
    spec:
      containers:
      - name: ui
        image: reportportal/service-ui:5.7.4
        ports:
        - containerPort: 8080
        env:
        - name: RP_SERVER_PORT
          value: "8080"
        - name: RP_API_BASE
          value: "http://reportportal-api:8585"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-ui
  namespace: reportportal
spec:
  selector:
    app: reportportal-ui
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
