---
apiVersion: v1
kind: Namespace
metadata:
  name: reportportal
  labels:
    name: reportportal

---
apiVersion: v1
kind: Secret
metadata:
  name: reportportal-secrets
  namespace: reportportal
type: Opaque
stringData:
  postgres-password: "reportportal123"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: reportportal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reportportal"
        - name: POSTGRES_USER
          value: "rpuser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: reportportal
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-all-in-one
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-all-in-one
  template:
    metadata:
      labels:
        app: reportportal-all-in-one
    spec:
      containers:
      - name: reportportal
        image: reportportal/reportportal:5.7.4
        ports:
        - containerPort: 8080
        env:
        - name: RP_DB_HOST
          value: "postgres"
        - name: RP_DB_PORT
          value: "5432"
        - name: RP_DB_NAME
          value: "reportportal"
        - name: RP_DB_USER
          value: "rpuser"
        - name: RP_DB_PASS
          valueFrom:
            secretKeyRef:
              name: reportportal-secrets
              key: postgres-password
        - name: RP_SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-all-in-one
  namespace: reportportal
spec:
  selector:
    app: reportportal-all-in-one
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
