---
apiVersion: v1
kind: Namespace
metadata:
  name: reportportal
  labels:
    name: reportportal

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-postgres
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-postgres
  template:
    metadata:
      labels:
        app: reportportal-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reportportal"
        - name: POSTGRES_USER
          value: "rpuser"
        - name: POSTGRES_PASSWORD
          value: "reportportal123"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-postgres
  namespace: reportportal
spec:
  selector:
    app: reportportal-postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-app
  namespace: reportportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-app
  template:
    metadata:
      labels:
        app: reportportal-app
    spec:
      containers:
      - name: reportportal
        image: reportportal/reportportal:latest
        ports:
        - containerPort: 8080
        env:
        - name: RP_DB_HOST
          value: "reportportal-postgres"
        - name: RP_DB_PORT
          value: "5432"
        - name: RP_DB_NAME
          value: "reportportal"
        - name: RP_DB_USER
          value: "rpuser"
        - name: RP_DB_PASS
          value: "reportportal123"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: reportportal-app
  namespace: reportportal
spec:
  selector:
    app: reportportal-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
