apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: demo-app
          image: localhost:5001/demo-app@sha256:0000000000000000000000000000000000000000000000000000000000000000
          env:
            - name: APP_VERSION
              value: "qa"
            - name: ENV
              value: "qa"
