apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
resources:
  - ../base
patches:
  - path: env-patch.yaml
# Image digest is the ONLY field updated by scripts/update-gitops-digest.sh
images:
  - name: localhost:5001/demo-app
    digest: sha256:8fefda56d04d451711b24caddd5dff620a669437026daecbfca4cb7f62aa8da9
