global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pipeline-metrics'
    static_configs:
      - targets: ['localhost:9091']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['213.109.162.134:30100']
    metrics_path: /api/monitoring/metrics
    scrape_interval: 30s
