name: Simple Auto Update Dashboard

on:
  push:
    paths:
      - 'repos-to-scan.yaml'

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Read Repository Info
      id: repo_info
      run: |
        # Extract repository information from repos-to-scan.yaml
        REPO_URL=$(grep -A 20 "repositories:" repos-to-scan.yaml | grep "^\s*- url:" | head -1 | sed 's/.*url: //' | tr -d ' ')
        REPO_NAME=$(grep -A 20 "repositories:" repos-to-scan.yaml | grep "^\s*name:" | head -1 | sed 's/.*name: //' | tr -d ' ')
        REPO_BRANCH=$(grep -A 20 "repositories:" repos-to-scan.yaml | grep "^\s*branch:" | head -1 | sed 's/.*branch: //' | tr -d ' ')
        
        echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "repo_branch=$REPO_BRANCH" >> $GITHUB_OUTPUT
        
        echo "Repository: $REPO_NAME"
        echo "URL: $REPO_URL"
        echo "Branch: $REPO_BRANCH"
        
    - name: Create GitHub Issue for Dashboard Update
      run: |
        echo "Creating GitHub issue for dashboard update..."
        
        REPO_NAME="${{ steps.repo_info.outputs.repo_name }}"
        REPO_URL="${{ steps.repo_info.outputs.repo_url }}"
        
        if [ -n "$REPO_NAME" ] && [ "$REPO_NAME" != "friendly-name" ]; then
          gh issue create \
            --title "🔄 Dashboard Updated for $REPO_NAME" \
            --body "## Dashboard Auto-Update Success
            
            **Repository:** $REPO_NAME
            **URL:** $REPO_URL
            **Updated:** $(date)
            
            The dashboard has been automatically updated to show data for the new repository.
            
            **Dashboard URL:** http://213.109.162.134:30102/d/6c8598d8-895f-4289-89d8-3ad3592da8ab/pipeline-dashboard-neuropilot-project
            
            **What was updated:**
            - Repository name and URL
            - Pipeline metrics
            - Test results
            - Security vulnerabilities
            - Code quality metrics
            
            This update was triggered automatically by changes to \`repos-to-scan.yaml\`.
            
            **Status:** ✅ Successfully updated"
        else
          echo "No valid repository found in repos-to-scan.yaml"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
